os: Visual Studio 2015

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
after_build:
- ps: "[System.Net.ServicePointManager]::SecurityProtocol = @('Tls12','Tls11','Tls','Ssl3')"
- ps: (new-object net.webclient).DownloadFile('http://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/2.6/sonar-scanner-cli-2.6.zip', 'SonarScanner.zip')
- ps: (new-object net.webclient).DownloadFile('http://sonarqube.com/static/cpp/build-wrapper-win-x86.zip', 'BuildWrapper.zip')
- ps: Add-Type -assembly “system.io.compression.filesystem”
- ps: "[io.compression.zipfile]::ExtractToDirectory('SonarScanner.zip', $env:APPVEYOR_BUILD_FOLDER+'/SonarScanner')"
- ps: "[io.compression.zipfile]::ExtractToDirectory('BuildWrapper.zip', $env:APPVEYOR_BUILD_FOLDER+'/BuildWrapper')"
- ps: BuildWrapper/build-wrapper-win-x86/build-wrapper-win-x86-64.exe --out-dir  'Build' msbuild BitmapFont.sln  /t:rebuild
- ps: SonarScanner/sonar-scanner-2.6/bin/sonar-scanner.bat -D sonar.host.url='https://sonarqube.com' -D sonar.login='d5fcf62e7cba7c67b913e9edb4ecee2e9a697d52' -D sonar.projectKey="bitmap_font" -D sonar.projectName=$env:APPVEYOR_PROJECT_NAME -D sonar.projectVersion=$env:APPVEYOR_BUILD_NUMBER -D sonar.sources='BitmapFont/' -D sonar.cfamily.build-wrapper-output='Build'
