os: Visual Studio 2015

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
after_build:
- ps: (new-object net.webclient).DownloadFile('http://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/2.6/sonar-scanner-cli-2.6.zip', 'SonarScanner.zip')
- ps: Add-Type -assembly “system.io.compression.filesystem”
- ps: "[io.compression.zipfile]::ExtractToDirectory('SonarScanner.zip', 'SonarScanner')"
- ps: SonarScanner/sonar-scanner-2.6/bin/sonar-scanner.bat -D sonar.host.url='https://sonarqube.com' -D sonar.login='d5fcf62e7cba7c67b913e9edb4ecee2e9a697d52' -D sonar.projectKey=$(appveyor_project_id) -D sonar.projectName=${appveyor_project_name} -D sonar.projectVersion=${appveyor_build_number} -D sonar.sources=${appveyor_build_folder}\BitmapFont -D sonar.cfamily.build-wrapper-output.bypass=true
