os: Visual Studio 2015

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
after_build:
- ps: .\SonarQubeAnalysis.ps1 -hostUrl 'https://sonarqube.com' -login  d5fcf62e7cba7c67b913e9edb4ecee2e9a697d52 -sources BitmapFont/ -projectName 'Bitmap Font' -projectKey 'bitmap_font' -projectVersion '1' -buildWrapperCommand "msbuild  BitmapFont.sln  /t:rebuild"
