os: Visual Studio 2015

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
after_build:
- ps: ./SonarQubeAnalysisForAppVeyor.ps1 -sources BitmapFont/ -buildWrapperCommand "msbuild  BitmapFont.sln  /t:rebuild"
