os: Visual Studio 2015

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
after_build:
- ps: .\SonarQubeAnalysis.ps1 -hostUrl $env:SONAR_HOST_URL -login $env:SONAR_TOKEN -sources BitmapFont/ -projectName $env:APPVEYOR_PROJECT_NAME -projectKey $env:APPVEYOR_PROJECT_SLUG -projectVersion $env:APPVEYOR_BUILD_NUMBER -buildWrapperCommand "msbuild  BitmapFont.sln  /t:rebuild"
